spring:
  profiles:
    active: test
  datasource:
    url:  jdbc:h2:mem:es_sample
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  elasticsearch:
    host: localhost
    port: 9200
    repositories:
      enabled: true
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
#elasticsearch logging
  org.springframework.data.elasticsearch: DEBUG